[package]
name = "rust-advent"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
miette = { version = "7.4", features = ["fancy"] }
nom = "7.1.3"
nom_locate = "4.2.0"
nom-supreme = "0.8.0"
